- hosts: all
  vars_files:
    - secrets.yaml
  tasks:
    - name: Init a new swarm with default parameters
      community.docker.docker_swarm:
        state: present
      
    - name: Ensure hashdb.sqlite exists
      copy:
        content: ""
        dest: ~/hashdb.sqlite
        force: false

    - name: Run bot docker service
      docker_swarm_service:
        name: createch-bot
        image: twobrowin/createch-bot:1.2.1
        mounts:
          - source: /home/user/hashdb.sqlite
            target: /hashdb.sqlite
            type: bind
        env:
          TZ: "Europe/Moscow"
          
          BOT_TOKEN:       "{{ bot_token }}"
          SHEETS_ACC_JSON: "{{ sheet_acc_json | string }}"
          SHEETS_LINK:     "{{ sheets_link }}"

          SWITCH_UPDATE_TIME:   '15'
          SETTINGS_UPDATE_TIME: '35'
          
          HASH_DB: /hashdb.sqlite
